### ISSUE TITLE
Sphinx API documentation

### ISSUE THREAD

**Issue by imranashraf** [QE-Lab/OpenQL#133]
generate documentation using [sphinx](http://www.sphinx-doc.org/en/master/)

**Comment by AdriaanRol** [comment]
@imranashraf I like the new sphinx docs but noticed that the API is not documented there even though it does exist in the deprecated "doc" folder #281 . We should try to include this in the main docs.

**Comment by imranashraf** [comment]
being done in PR https://github.com/QE-Lab/OpenQL/pull/286
