### ISSUE TITLE
Open Open QL 

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#15]
@imranashraf @Nader-Khammassi 

I would like the OpenQL repository to be an open repository. @imranashraf told me that we just need an OK from @Nader-Khammassi . 

I think this is important for several reasons in addition to the general open source stuff 
- it allows easier integration with PycQED as I can make my test code dependent on OpenQL. This is essential for driving the development IMO. 
- it allows free automation of the tests that @imranashraf already made for OpenQL. 

I think that both reasons make this something we really want to do.

**Comment by imranashraf** [comment]
as it is open now, so closing this issue
