### ISSUE TITLE
Inclusion of compensation pulses in output of the compiler 

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#20]
Whenever we apply a 2 qubit gate (CZ) we do this using flux pulses. 

Before we initialize for a next experiment ("subcircuit") we need to discharge our bias tee. We do this by applying all the Flux pulses in reverse (same pulse but negative amplitude). This should be included in the output of the compiler. 

@imranashraf we should probably discuss this in a bit more detail at our next meeting.

**Comment by wvlothuizen** [comment]
outdated
