### ISSUE TITLE
invalid Kernel names should raise error

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#200]
Not all names are allowed to be names of Kernels. 

In the recent (0.5.4) version, kernels automatically get added to .qisa files as labels. Sometimes this creates invalid .qisa (that can not assemble). 
I don't know what the exact constraints are, but a few examples are 
- starting with the letter `s` followed by a number (gets interpreted as a bundle instruction) 
- containing a `.`. character, gets interpreted as an instruction (that does not exist). 

Specifying a kernel with such a name compiles fine, only raising an exception when trying to use the generated (invalid qisa). 

The correct behaviour should be either 
- raise an error upon specifying a Kernel name that is invalid (while being clear about the constraints that apply) 
- parse out illegal characters to ensure unique character names (as this is only used internally in the qisa). 

@imranashraf

**Comment by imranashraf** [comment]
closing due to no response
