### ISSUE TITLE
Unitary Decomposition

### ISSUE THREAD

**Issue by anneriet** [QE-Lab/OpenQL#205]
Adding support for unitary decomposition.
Input should be unitary_decomp(qubits,matrix), output should be QASM code of rz and ry gates and cnot operations.

**Comment by prince-ph0en1x** [comment]
@anneriet If this is merged (at least to a tested workable level), shall @imranashraf resolve this?

**Comment by imranashraf** [comment]
This is not yet merged. we can merge it if:
- implementation is complete
- we have tests for the implementation
- documentation

**Comment by Akankshipriya** [comment]
openql has no attribute Unitary??

**Comment by Akankshipriya** [comment]
Traceback (most recent call last):
  File "new.py", line 6, in <module>
    u_unitary = Unitary("U_name",U)
NameError: name 'Unitary' is not defined

**Comment by Akankshipriya** [comment]
Traceback (most recent call last):
  File "new.py", line 6, in <module>
    u_unitary = ql.Unitary("U_name",U)
AttributeError: module 'openql' has no attribute 'Unitary'

**Comment by anneriet** [comment]
Hey, which version of OpenQL are you using? For me it works when building OpenQL from the current "develop" branch

**Comment by Akankshipriya** [comment]
Can you please describe how to install latest version of openql with all dependences.
I try to install it by command pip qutechopenql.

**Comment by anneriet** [comment]
That's in the docs: https://openql.readthedocs.io/en/latest/installation.html#compilation-from-sources

**Comment by Akankshipriya** [comment]
I already done this. It is not working for me.

**Comment by Akankshipriya** [comment]
Please describe all possible command sequence.

**Comment by anneriet** [comment]
For me, 
cd OpenQL
git submodule update --init --recursive
sudo python setup.py install --user
works (is basicaly the same as the docs), make sure to (manually) install all the necessary packages and update the submodules (git submodule update --init --recursive), but I cannot help you more than this, and this is on linux, I would have no clue for windows or macOS.

**Comment by Akankshipriya** [comment]
These command gives me this Error:
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    copyfile(clib, clibSwig)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ajay/Desktop/OpenQL/cbuild/swig/_openql.so'

**Comment by Akankshipriya** [comment]
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    copyfile(clib, clibSwig)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Desktop\\OpenQL\\cbuild\\swig\\_openql.pyd'

**Comment by razvnane** [comment]
With the addition of the Eigen library and some other changes in the backed. the windows compilation got broken. It should be fixed now though with PR #327. Let me know if it works so we can close this issue.
