### ISSUE TITLE
wait instruction semantics changed by recent changes to scheduler.h

### ISSUE THREAD

**Issue by wvlothuizen** [QE-Lab/OpenQL#222]
Until recently, the program below would not schedule "rym90" in parallel with "ry90". After  recent changes to scheduler.h the "wait" seems to be ignored and the instructions are scheduled in parallel (scheduler=ALAP, scheduler_uniform=no, not resource constraint).

The log file does show the following, which may be related:
```
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2314 Scheduling ALAP [DONE]
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2235 bundler ...
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2244 ... ignoring: wait 0
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2244 ... ignoring: wait 0
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2244 ... ignoring: wait 0
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2244 ... ignoring: wait 0
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2289 Depth: 39
[OPENQL] /mnt/mac/GIT/OpenQL/ql/scheduler.h:2290 bundler [DONE]

```

The program:
```
    k.gate("ry90", x);
    k.gate("ry90", xN);
    k.gate("ry90", xE);
    k.gate("ry90", xW);
    k.gate("ry90", xS);
    k.wait({x, xN, xE, xW, xS}, 0);

    k.gate("measure", std::vector<size_t> {x}, std::vector<size_t> {0});
    k.wait({x}, 0);

    k.gate("rym90", z);
```

**Comment by wvlothuizen** [comment]
It seems that this can be worked around by waiting on all defined qubits instead of just a subset

**Comment by imranashraf** [comment]
It should also work even when you are waiting on single qubit.
@wvlothuizen you can still get the old behaviour by setting the option:
`opt_name2opt_val["scheduler_post179"] = "no";`

@jvansomeren can you please look into it.

**Comment by wvlothuizen** [comment]
I already tried 
`opt_name2opt_val["scheduler_post179"] = "no";
`
but that does not seem to help

**Comment by jvansomeren** [comment]
The current semantics of wait {set of qubits} value is that dependences are created only for the operand qubits with a duration of value (multiplied by a cycle length in nanoseconds). Somehow the old semantics got lost in the update; what was it?

**Comment by wvlothuizen** [comment]
In the old semantics, calling kernel.h function "void wait(std::vector<size_t> qubits, size_t duration)" with duration=0 would finish operations on <qubits> before other gates are performed, also see the opening example of this issue. This seems to be in line with the only documentation I could find (in openql.i) states "inserts explicit wait on specified qubits.". 

I don't necessarily object to changing the semantics, but I do think the change and the new behaviour should be well documented.

**Comment by jvansomeren** [comment]
Hi Wouter,

The old semantics that you describe should also be the new semantics.
I’ll check scheduling your program and find out what is wrong.
I suspect that the 0 duration in the argument doesn’t get into the gate as duration.

Best,

Hans

Op 8 apr. 2019, om 16:32 heeft Wouter Vlothuizen <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


In the old semantics, calling kernel.h function "void wait(std::vector<size_t> qubits, size_t duration)" with duration=0 would finish operations on before other gates are performed, also see the opening example of this issue. This seems to be in line with the only documentation I could find (in openql.i) states "inserts explicit wait on specified qubits.".

I don't necessarily object to changing the semantics, but I do think the change and the new behaviour should be well documented.

**Comment by imranashraf** [comment]
the intent is not to change this semantics. essentially wait instruction with duration = 0 is a barrier.

**Comment by jvansomeren** [comment]
Wouter wrote about the documented semantics of wait:
        inserts explicit wait **on specified qubits**
while he seems to imply in his remarks that he expects it to be:
        insert explicit wait on all qubits ignoring the specified qubit list

I am confused now  on the meaning of the list of qubits given to the wait.

The quoted semantics implies that the rym90 on z gets in parallel with the measure (ALAP)
or the y90s (ASAP), since the z is not mentioned in any wait qubit list.
This behavior is what was implemented in the pre179 and is implemented in the post179 scheduler.
So I fail to reproduce his specified behavior.

When the wait semantics would be:
        insert explicit wait on all qubits ignoring the specified qubit list
then the rym90 would not be in parallel with anything.
But this is not the behavior of the old and of the new code
so would mean a change of semantics.

**Comment by wvlothuizen** [comment]
I don't have a clear idea on what the semantics were exactly, neither on what they should be. I just had the problem that I had a program that used to work, and stopped working after the new scheduler became part of OpenQL. 
In this particular program the wait was present to force the scheduler to move all subsequent gates into a different bundle, and that worked. The intended behaviour can now be obtained by waiting on all qubits.
So I do have a work around to get what I want, but I do need program changes to obtain that. Other users using the wait in the same way might see their code break by the new version.

**Comment by imranashraf** [comment]
@wvlothuizen I just tested the code snippet you posted as:

```python
        x, xN, xE, xW, xS, z = 0, 1, 2, 3, 4, 5 

        k.gate('ry90', [x])
        k.gate('ry90', [xN])
        k.gate('ry90', [xE])
        k.gate('ry90', [xW])
        k.gate('ry90', [xS])
        k.gate('barrier', [x, xN, xE, xW, xS])
        # which is same as:
        # k.gate('wait', [x, xN, xE, xW, xS], 0)

        k.gate('measure', [x])
        k.gate('barrier', [x])
        # which is same as:
        # k.gate('wait', [x], 0)

        k.gate('rx90', [z])

        p.add_kernel(k)
        p.compile()
```
The complete test is available on branch bug/222-wait-semantics in test_wait.py with the name **test_wait_barrier_222**.

This generates the following scheduled cqasm for ALAP:

```
    { ry90 q[0] | ry90 q[1] | ry90 q[2] | ry90 q[3] | ry90 q[4] }
    wait 1
    { measure q[0] | rx90 q[5] }
    wait 1
```
which is as per definition of barrier/wait as we are not waiting on q[5] so it is scheduled ALAP.

Similarly, the ASAP scheduled cqasm is:
```
    { ry90 q[0] | ry90 q[1] | ry90 q[2] | ry90 q[3] | ry90 q[4] | rx90 q[5] }
    wait 1
    measure q[0]
    wait 1
```
which is also as expected as we are not waiting on q[5] so it can be scheduled ASAP.

**Comment by wvlothuizen** [comment]
Just to verify my original reason for submitting this issue, and to point more explicitly to the problem, I reran my test program from 2 old commits:

**Still working:**
```
commit 9dc5f2b7bff77c3c76690b118184311386b1c8be
Merge: 227a949 450f4ec
Author: Imran Ashraf <iimran.aashraf@gmail.com>
Date:   Tue Feb 19 12:30:13 2019 +0500

    Merge pull request #214 from alxhotel/fix_instruction_name_json
    
    Fix instruction names in hardware config file
```

Build en run:
```
vmwouter:/mnt/mac/GIT/OpenQL/cbuild> git checkout 9dc5f2b7bff77c3c76690b118184311386b1c8be
vmwouter:/mnt/mac/GIT/OpenQL/cbuild> make test_cc
vmwouter:/mnt/mac/GIT/OpenQL/tests/cc> ../../cbuild/tests/test_cc

```
completes without error

**Failing:**
```
commit 661b92fa70c8862095b2dcb3b220d84084f779a8
Merge: 00d5df4 9dc5f2b
Author: Imran Ashraf <iimran.aashraf@gmail.com>
Date:   Thu Mar 14 18:41:03 2019 +0100

    merged develop
```

Result:
```
vmwouter:/mnt/mac/GIT/OpenQL/tests/cc> ../../cbuild/tests/test_cc
[...]
## Bundle 5, start_cycle=10, duration_in_cycles=1):
 # gate 'ry90 12'
  # slot=0, group=0, instrument='awg8-mw-0', signal='["ry90-awg8-mw-0:0-gi","ry90-awg8-mw-0:0-gq","ry90-awg8-mw-0:0-di","ry90-awg8-mw-0:0-dq"]'
  # slot=2, group=0, instrument='vsm-0', signal='["dummy"]'
 # gate 'ry90 6'
  # slot=0, group=0, instrument='awg8-mw-0', signal='["ry90-awg8-mw-0:0-gi","ry90-awg8-mw-0:0-gq","ry90-awg8-mw-0:0-di","ry90-awg8-mw-0:0-dq"]'
  # slot=2, group=0, instrument='vsm-0', signal='["dummy"]'
 # gate 'ry90 8'
  # slot=0, group=1, instrument='awg8-mw-0', signal='["ry90-awg8-mw-0:1-gi","ry90-awg8-mw-0:1-gq","ry90-awg8-mw-0:1-di","ry90-awg8-mw-0:1-dq"]'
  # slot=2, group=1, instrument='vsm-0', signal='["dummy"]'
 # gate 'ry90 2'
  # slot=0, group=1, instrument='awg8-mw-0', signal='["ry90-awg8-mw-0:1-gi","ry90-awg8-mw-0:1-gq","ry90-awg8-mw-0:1-di","ry90-awg8-mw-0:1-dq"]'
  # slot=2, group=1, instrument='vsm-0', signal='["dummy"]'
 # gate 'ry90 7'
  # slot=1, group=1, instrument='awg8-mw-1', signal='["ry90-awg8-mw-1:1-gi","ry90-awg8-mw-1:1-gq","ry90-awg8-mw-1:1-di","ry90-awg8-mw-1:1-dq"]'
  # slot=2, group=3, instrument='vsm-0', signal='["dummy"]'
 # gate 'rym90 11'
  # slot=1, group=1, instrument='awg8-mw-1', signal='["rym90-awg8-mw-1:1-gi","rym90-awg8-mw-1:1-gq","rym90-awg8-mw-1:1-di","rym90-awg8-mw-1:1-dq"]'

[OPENQL] /mnt/mac/GIT/OpenQL/ql/arch/cc/codegen_cc.h:379 Error: Signal conflict on instrument='awg8-mw-1', group=1, between '["ry90-awg8-mw-1:1-gi","ry90-awg8-mw-1:1-gq","ry90-awg8-mw-1:1-di","ry90-awg8-mw-1:1-dq"]' and '["rym90-awg8-mw-1:1-gi","rym90-awg8-mw-1:1-gq","rym90-awg8-mw-1:1-di","rym90-awg8-mw-1:1-dq"]'
terminate called after throwing an instance of 'ql::exception'
  what():  Error : Signal conflict on instrument='awg8-mw-1', group=1, between '["ry90-awg8-mw-1:1-gi","ry90-awg8-mw-1:1-gq","ry90-awg8-mw-1:1-di","ry90-awg8-mw-1:1-dq"]' and '["rym90-awg8-mw-1:1-gi","rym90-awg8-mw-1:1-gq","rym90-awg8-mw-1:1-di","rym90-awg8-mw-1:1-dq"]'
Abort

```

The failure occurs in tests/cc/test_cc.cc::test_qec_pipelined() because the 'rym90 11' conflicts with 'ry 90 *'. Note that the CC backend uses cc_light_schedule() here, not cc_light_schedule_rc(), so resource constraints are not taken into account. 

Between the two commits quoted, nothing significant was changed to the test program or the CC backend, but the scheduler was changed extensively, as can be seen by a 'git diff 9dc5f2b7bff77c3c76690b118184311386b1c8be'

Regarding the scheduled qasm, I recently found out that that is generated by a scheduling function (i.c. program.h::schedule) that is different from that used by the backend, so there may be differences with respect to the actual scheduling.

**Comment by imranashraf** [comment]
PR https://github.com/QE-Lab/OpenQL/pull/228 documents and tests variants of waits and tests. IMHO we can close this issue.

**Comment by wvlothuizen** [comment]
no problem, since the original test program works with a small change, and I also recently verified a large part of our pycQED test suite to still work (with the CC backend that is)
