### ISSUE TITLE
support for barrier_all() operation

### ISSUE THREAD

**Issue by imranashraf** [QE-Lab/OpenQL#225]
currenty barrier() expects a list of qubits. For surface-7, when we have to add a barrier for all the 7 qubits, we have to mention all the 7-qubits. On the same lines, for surface-17, all the 17 qubits would be required as an argument. 

A simple solution to make a barrier for all the qubits while being surface agnostic would be add the support for barrier_all().

**Comment by jvansomeren** [comment]
Hi Imran,
I can Also make a simple change that probably makes wait semantics compatible again: a wait without arguments behaves as a wait with all registers as arguments
See Also the behavior of display


Groet,

Hans

Op 17 apr. 2019 om 03:07 heeft Imran Ashraf <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


currenty barrier() expects a list of qubits. For surface-7, when we have to add a barrier for all the 7 qubits, we have to mention all the 7-qubits. On the same lines, for surface-17, all the 17 qubits would be required as an argument.

A simple solution to make a barrier for all the qubits while being surface agnostic would be add the support for barrier_all().

**Comment by imranashraf** [comment]
@jvansomeren this is what i did on https://github.com/QE-Lab/OpenQL/tree/enh/barrier_all-225 branch.
