### ISSUE TITLE
faster compilation by launching multiple parallel compilation

### ISSUE THREAD

**Issue by imranashraf** [QE-Lab/OpenQL#229]
during debugging it is desirable to have faster compilation by launching multiple threads for compilation. this should be done such that user can set an environment variable to control the number of parallel jobs.

**Comment by wvlothuizen** [comment]
I agree that faster compilation would be great, but wouldn't expect parallel compilation to help a lot because almost everything is in header files

**Comment by imranashraf** [comment]
agree. still on my 4 core vm it saves ~24 sec due to the parallel compilation of lemon files, which is still something when you have to do this (re)compilation multiple times.

**Comment by mjwoudstra** [comment]
Compilation can probably be sped up a lot more by moving implementations from header files into .cpp files and minimizing dependencies.

**Comment by imranashraf** [comment]
indeed. but that should be the discussion/work of separate issue.
