### ISSUE TITLE
tests/test_mapper.cc doesn't compile

### ISSUE THREAD

**Issue by jvansomeren** [QE-Lab/OpenQL#245]
Compiling in the develop branch tests/test_mapper.cc:
```
#include <openql.h>
#include "utils.h"

int main(int argc, char ** argv)
{
    ql::utils::logger::set_log_level("LOG_NOTHING");
}
```
fails while linking it; see screenshot:

![Screenshot at 2019-10-28 10-43-12](https://user-images.githubusercontent.com/17248438/67668711-c5b2e600-f970-11e9-8843-fa02e5fad671.png)

Please note that utils.h defines:
         `    extern log_level_t LOG_LEVEL;`
and that subsequent lines use it; those give rise to the errors.
The errors mean that there is no real variable/constant allocated for LOG_LEVEL.
In src/platform.cc there is a definition:
```
namespace ql { namespace utils { namespace logger {
    log_level_t LOG_LEVEL;
}}}
```
but this src/platform.cc is obviously not linked in the image of tests/test_mapper

**Comment by imranashraf** [comment]
@jvansomeren  https://github.com/QE-Lab/OpenQL/pull/278 fixes the issue, give it a try.

**Comment by jvansomeren** [comment]
Thanks, but not today, since I’m at home and my desktop at the TUD is down.

Best,

Hans

Op 27 nov. 2019, om 13:12 heeft Imran Ashraf <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


@jvansomeren<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jvansomeren&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=5TDvp4TeEveDyhHvI5bjI0gwMqksNxDKyW4duor4siw&s=aViW3fohpD3VN9io-k1ATjXO8Ca7kPw0GxBQsF3_HxE&e=> #278<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_QE-2DLab_OpenQL_pull_278&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=5TDvp4TeEveDyhHvI5bjI0gwMqksNxDKyW4duor4siw&s=oJneyvkmnKI0qmtEN8TgKWx7BCKTNB7z7qhh2rzoGO8&e=> fixes the issue, give it a try.
