### ISSUE TITLE
Name change required for pypi

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#260]
There is a naming conflict with an existing package on PyPi. As such we will need to make a name change. 

Carmina will come with a proposal on the name change and how to execute this.

**Comment by AdriaanRol** [comment]
@carminaga

**Comment by imranashraf** [comment]
As per https://github.com/QE-Lab/OpenQL/pull/276, openql is now available on pypi with the distribution name **qutechtools**.
