### ISSUE TITLE
Compilation-chain modularity

### ISSUE THREAD

**Issue by MiguelSMoreira** [QE-Lab/OpenQL#266]
It is important that mechanisms are developed to allow greater modularity in the use of OpenQL. Users should be able to specify which compiler passes (scheduler, mapper, optimizers, etc) are used for a specific run, and developers should be able to contribute with additional modules for new functionality. In this way, allowing for a modular compilation chain in OpenQL would support new use cases and easier development of new compiler features.

Documentation on the following subjects would be indispensable for implementation of the suggested features:
i) available compilation passes (and respective configuration and functionality)
ii) compiler inter-module interfaces (intermediate circuit representations)

The discussions on intermediate representation languages, in issue #255, and on transpilation capabilities, issue #272, are of high relevance in the context of this issue.

**Comment by razvnane** [comment]
![oql-v0 9-api-seqdia](https://user-images.githubusercontent.com/14236280/78233015-6a63c180-74d5-11ea-957b-c547fbe3fe49.png)

**Comment by razvnane** [comment]
@
![oql-v 0 9-api-classdia](https://user-images.githubusercontent.com/14236280/78233340-da724780-74d5-11ea-9755-c8b017ab295d.png)

**Comment by MiguelSMoreira** [comment]
Functionally tested in the lab
