### ISSUE TITLE
Transpilation capabilities to increase code generation efficiency

### ISSUE THREAD

**Issue by MiguelSMoreira** [QE-Lab/OpenQL#272]
This issue is meant to highlight the need to add transpilation capabilities to OpenQL, as a way to increase the efficiency of code generation and support new use-cases.
The desired functionality may flow naturally from the capabilities described in issue #266, on compilation-chain modularity, as that request may be understood to mean full flexibility in the choice of compilation passes by the user (in which case, transpilation is naturally supported). However, less involved approaches may be taken to support transpilation use-cases sooner.

Issue #255, on intermediate representation languages, is also relevant in the context of this issue.

**Comment by jvansomeren** [comment]
Work is underway by Fer Grooteman f.j.grooteman@tudelft.nl to integrate a cqasm reader into OpenQL. This cqasm reader reads CQASM 1.0 and creates an internal circuit representation of it. This cqasm_reader has been tested in the dclab context and is about to be integrated in the develop branch of the OpenQL repository.
