### ISSUE TITLE
remove deprecated "doc" folder

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#281]
While trying to build the "docs" locally I encountered the "doc" folder. This seems to contain old (and probably deprecated) documentation and examples. It is good practice to not have things in two places. I suggest we remove the old doc folder.

**Comment by jvansomeren** [comment]
Imran proposed to add API documentation to the Sphinx doc in an automated way; then doc/api can be removed.
The configuration_specification.md is superseded by docs/platform* and can be deleted.
I don't have an opinion on notebooks.

**Comment by AdriaanRol** [comment]
@jvansomeren I would love to see a sphinx autodoc for the API. I think the notebooks are mostly outdated by now so I think the we should probably mark them as such. If we want to include notebook examples as part fo the documentation (which can be a good idea), there are two options, we could use `jupyter-sphinx` https://jupyter-sphinx.readthedocs.io/en/latest/ which is a pretty cool extension that allows us to include notebooks directly in the sphinx docs or (so we don't have to set this up) we could just provide a link to the notebooks from the docs.

**Comment by imranashraf** [comment]
being done in https://github.com/QE-Lab/OpenQL/pull/286
