### ISSUE TITLE
CC backend fails with unclear error message on misconfiguration

### ISSUE THREAD

**Issue by wvlothuizen** [QE-Lab/OpenQL#292]
The following configuration fragment:
```
				"awg8-mw-direct-iq": {				      // just I&Q to generate microwave without VSM. HDAWG8: "new_novsm_microwave"
					"control_bits": [
						[6,5,4,3,2,1,0],                  // group 0
						[13,12,11,10,9,8,7],              // group 1
						[22,21,20,19,18,17,16],           // group 2. NB: starts at bit 16 so twin-QWG can also support it
						[29,28,27,26,25,24,23]            // group 4
					],
					"trigger_bits": [31,15]

```
Gives the following error:
![pastedImage](https://user-images.githubusercontent.com/10208538/74918054-d6c4ae80-53c8-11ea-88a8-4e0e42806048.png)

**Comment by jvansomeren** [comment]
Hi Wouter,

I would suggest trying
to add after line 465 of src/program.cc a "return 0;"
i.e. after the call to the back_end_compiler's compile() method.

Best,

Hans

**Comment by jvansomeren** [comment]
Sorry, wrong suggestion.

**Comment by wvlothuizen** [comment]
solved by handling all JSON access properly in class settings_cc
