### ISSUE TITLE
OpenQL documentation is hard to read

### ISSUE THREAD

**Issue by jvansomeren** [QE-Lab/OpenQL#300]
An entry-level to the OpenQL documentation is needed.

Another complicating aspect is that it describes more detail than currently available.
The latter is caused by that the documentation was written with the modularity changes (create passes, create independent IR, make interface with back-end more clear) in mind, while still describing the current system.
Proposal is to review the documentation for this aspect when the modularity changes are in place. Hopefully the system is then easier to understand and by that the documentation easier to read.

**Comment by MiguelSMoreira** [comment]
Hans and Wouter provided first review
