### ISSUE TITLE
Hierarchical Gate Decomposition

### ISSUE THREAD

**Issue by MiguelSMoreira** [QE-Lab/OpenQL#308]
Even though gate decomposition is currently supported in OpenQL, its implementation does not allow for a decomposition to make use of a gate specified as a decomposition itself. Therefore, this restricts the abstraction level allowed by the compiler.

This issue is aimed at discussing the advantages of supporting this behavior, how it should be specified and potential implementations that would allow it.

**Comment by NoahGWood** [comment]
I actually found this project by searching for this **exact** feature!

I'm working on a circuit synthesizer for the KLM protocol, basically it takes in QASM code and outputs gerber files for PCB manufacturing. Right now we're using a reduced set of gates with no support for custom gates, if we could decompose a gate into a collection of other gates, we'd be able to synthesize just about any algorithm into physical hardware. With that and the rest of our software and hardware we'll have a practical (and affordable) road to market for quantum hardware.

Looking at your work, it seems it would be easier for us to re-build our software to integrate with your compiler, and I think that's what we'll do

**Comment by MiguelSMoreira** [comment]
@wvlothuizen it would also be important for us to test the new "decomposition after scheduling" features recently implemented

**Comment by MiguelSMoreira** [comment]
Backwards compatibility has already been tested in the Lamborghini setup. New functionality should be tested with an upgraded configuration file before this issue is closed

**Comment by MiguelSMoreira** [comment]
Having attempted to test hierarchical gate decompositions of "fluxdance" step 1 into its constituents (in this example, a cz operation between q8 and q10, and between q9 and q11), we found out that OpenQL was not capable of further decomposing those operations into their own decompositions (in this example, used to translate cz operations into their equivalents with parking on the respective qubits).

Small change in PycQED for this test was tracked in commit a3bf706 of the feature/cc branch.

**Comment by jvansomeren** [comment]
Hi,
So is this a problem?
Can you then be more specific
About the context of this?

Groet,

Hans van Someren



Op 18 jan. 2022 om 15:03 heeft Miguel Serrão Moreira ***@***.***> het volgende geschreven:

﻿

Having attempted to test hierarchical gate decompositions of "fluxdance" step 1 into its constituents (in this example, a cz operation between q8 and q10, and between q9 and q11), we found out that OpenQL was not capable of further decomposing those operations into their own decompositions (in this example, used to translate cz operations into their equivalents with parking on the respective qubits).

Small change in PycQED for this test was tracked in commit a3bf706 of the feature/cc branch.

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_QE-2DLab_OpenQL_issues_308-23issuecomment-2D1015441887&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=12pE3pOrxYdd76BKOhZLL6nIW9cgeAKTk0h7cp2QeWM&s=k0VtnGOvXOO-TfFCxqePXqBmcXCbUFfVJ098GnEFLhE&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEDTBNQVNQOK5CDQJ5QB3KDUWVXMJANCNFSM4MJXENJQ&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=12pE3pOrxYdd76BKOhZLL6nIW9cgeAKTk0h7cp2QeWM&s=zD73yx79yj7hG5RfVb6bSEPfypSyhzegHLKA9GhaW54&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=12pE3pOrxYdd76BKOhZLL6nIW9cgeAKTk0h7cp2QeWM&s=NgcsD0255oi43O461ehW8F8TPmgRBW2LXg8-meNadqU&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=kNdT9ewT6pQdYFkBLR_5-ZqsrSTk7k5Hdd7MSC_Vnzg&m=12pE3pOrxYdd76BKOhZLL6nIW9cgeAKTk0h7cp2QeWM&s=J7iR5zPEhtJQNhy9IsNdXCEbrgru-3t3JaEGYWwZvwg&e=>.

**Comment by wvlothuizen** [comment]
Further testing shows that HGD does work as to be expected for the 'new style' gate decompositions, e.g.:

```
        "cz q8,q10": {
            "prototype": ["Z:qubit", "Z:qubit"],
            "duration": @FLUX_DURATION@,
            "decomposition": {
                "into": "_cz_sw_ne_park q[8],q[10],q[11]"
            }
        },
        "cz q10,q8": {
            "prototype": ["Z:qubit", "Z:qubit"],
            "duration": @FLUX_DURATION@,
            "decomposition": {
                "into": "cz q[8],q[10]"
            }
        },
```

where "cz 10,q8" correctly decomposes into "_cz_sw_ne_park q[8],q[10],q[11]".

Legacy gate decomposition does not support HGD (and never did).
