### ISSUE TITLE
Support for barrier operations in gate decomposition

### ISSUE THREAD

**Issue by MiguelSMoreira** [QE-Lab/OpenQL#309]
With this issue, I want to request support for the specification of barrier operations in gate decomposition. Support for this request has already been implemented in a fork of OpenQL by @wvlothuizen. Any input on the merit of this request or its initial implementation would be greatly appreciated.

**Comment by wvlothuizen** [comment]
duplicates #303

**Comment by MiguelSMoreira** [comment]
> duplicates #303

You are correct, my mistake.
Issue closed to avoid duplicates
