### ISSUE TITLE
Proper support for 2-qubit operations

### ISSUE THREAD

**Issue by MiguelSMoreira** [QE-Lab/OpenQL#312]
In this issue, I aim to address the limitations observed with **specifying 2-qubit operations in OpenQL**.
To give some context, a 2-qubit operation in the current control architecture _requires the triggering of up to three different waveforms_. One implements the operation itself, the second implements a phase-correction and there might be the need for a third, which would park another qubit at a different frequency. 

Currently, there is _only support for the specification of a single codeword per quantum gate_. Therefore, for a 2-qubit operation, both targets will be issued the same codeword. This will not allow the proper implementation of 2-qubit gates.

It is the goal of this issue to discuss ways to implement 2-qubit operations such that:
- all codewords are sent to their respective devices at the same time
- different codewords can be specified for each of the targets on which a gate can be called
- parking operations can be triggered simultaneously (being either explicitly set by the user, or inferred from the chip topology)

Do you have any ideas or comments on this, @wvlothuizen @jvansomeren ?

**Comment by wvlothuizen** [comment]
see my comment: https://github.com/QE-Lab/OpenQL/issues/303#issuecomment-616780610

**Comment by jvansomeren** [comment]
Some questions:
- which target(s) is/are meant? Only CC or also still CC-Light variants?
- does each qubit that is involved get just one codeword
Some remarks:
- this support (kind of decomposition) should be implemented after the rcscheduler to guarantee simultaneous execution
- it is code generation for the cz gate in terms of coding facilities of the target system
- in @wvlothuizen #303 comment use is made of specialized gates (matching of gate contains qubit ids); this was argued not to be scalable in the recent WP15 meeting by @MiguelSMoreira so is not preferred

**Comment by wvlothuizen** [comment]
Some answers and remarks:
- I think that the whole notion of codewords should be fully contained in the backend, since different hardware implementations (e.g. Qblox) may not use codewords at all
- it is generic that a quantum gate outputs a **vector** of waveforms
- https://github.com/QE-Lab/OpenQL/issues/303#issuecomment-616780610 concerns two related items:
  - an extension to the CC backend to allow specifying codewords per qubit parameter, in conjunction with two and three qubit operations (CZ and CZ with PARK)
  - the use of specialized gate expansion to handle the differences of gate implementation dependent on qubit location within the grid
- I do agree that the second item is not scalable, but on the other hand it is quite workable for the current 5 qubits, and also for 17 and a bit beyond. At this stage a big advantage is that it provides full control by the end user. And it can be available pretty soon.
 An algorithm (probably implemented as a compiler pass) is certainly required at some point, but it does depend on topology, strategy, qubit type, etc, and may be a bit of a black box to the end user. 
 Of course the two may live together...

**Comment by MiguelSMoreira** [comment]
> I think that the whole notion of codewords should be fully contained in the backend, since different hardware implementations (e.g. Qblox) may not use codewords at all
> * it is generic that a quantum gate outputs a **vector** of waveforms

Completely agree with this. The issue simply did not generalize to this notion since it was not fundamental to get a working system. Nevertheless, we should take this into consideration when thinking about solutions to this problem, such that we don't aggregate the notion of codewords any further in the compiler.

>   * an extension to the CC backend to allow specifying codewords per qubit parameter, in conjunction with two and three qubit operations (CZ and CZ with PARK)
>   * the use of specialized gate expansion to handle the differences of gate implementation dependent on qubit location within the grid

Scalability remarks apart (which I agree are not of the utmost relevance right now), this solution seems like a good compromise to me. Is this currently possible to define a three-qubit-flux operation like this?
```
 "cz_se_nw_park": {
            "duration": 80,
            "matrix": [ [0.0,1.0], [1.0,0.0], [1.0,0.0], [0.0,0.0] ],
            "type": "flux",
            "cc_light_instr": "cz",
            "cc": {
                "ref_signal": "three-qubit-flux", 
                "static_codeword_override": [2,4,5]  // codeword 2 on SE, 4 on NW, 5 on park
            }
        },
```

If so, why would we then require anything like the following decomposition:
` "cz q2 q3": ["cz_sw_ne_park q2,q3,q4]`

could we not simply create a configuration for a target-specific operation? With target-specific operation, I mean an operation for which its targets are fully specified, like in "cz q2 q3". I should also clarify that I use target as a term to denote the qubit on which an operation is applied.

**Comment by jvansomeren** [comment]
I would very much like to see the algorithm that we discussed during the meeting,
i.e. given the topology and a fully specialized operation such as "cz q2 q3",
which waveforms related to which qubits should be generated?
In which cases would an override be useful?

Note that the scheduler constraints will mimic this so have to know this as well
(the affected qubits cannot be involved in a parallel cz or rotation or measurement).
So I would prefer a description in the configuration file similar to the resource constraints,
i.e. similar to detune_qubits.
Speaking of the detune_qubits constraint, does it still apply?

Note that there is currently a decomposer pass that listens to cz_mode.
What is wrong with that? It seems that was targeting the same issue.

**Comment by MiguelSMoreira** [comment]
@wvlothuizen we should also test the triggering of multiple operations (across different instruments) through a single gate definition. An example would be the triggering of multiple flux pulses (for cz operations and parking) in addition to multiple microwave operations (virtual-z phase updates), with every CZ gate that is scheduled.

**Comment by wvlothuizen** [comment]
Tests to perform:

- [x] new flux gate decompositions from generate_CC_cfg_modular.py

**Comment by MiguelSMoreira** [comment]
We have tested the mechanism to translate a gate without parking into its equivalent with a corresponding parking operation. Furthermore, we tested the new 2-qubit gate decomposition scheme for arbitrary number of qubits, including for the specification of simultaneous parking operations.
