### ISSUE TITLE
Travis fails on QISA-AS

### ISSUE THREAD

**Issue by wvlothuizen** [QE-Lab/OpenQL#330]
see the screenshots below.

And a question: does anyone know why https://github.com/imranashraf/travis-libqasm.git and https://github.com/imranashraf/travis-eQASM_Assembler.git are used instead of those from QE-lab?

![image](https://user-images.githubusercontent.com/10208538/84650464-96a1b280-af08-11ea-9a7d-3ceac33c4a9e.png)

![image](https://user-images.githubusercontent.com/10208538/84650425-7f62c500-af08-11ea-9ddb-79343ebb1b2a.png)

**Comment by razvnane** [comment]
Solved in the new build system starting 0.8.1.dev4
