### ISSUE TITLE
Command line option 'output_dir' gets reset to default

### ISSUE THREAD

**Issue by wvlothuizen** [QE-Lab/OpenQL#378]
While switching from OpenQL 0.8.1 to the current version, it was observed that option 'output_dir' gets reset to default.

What we actually see is that we get '...test_output' (i.e. the default value) at https://github.com/DiCarloLab-Delft/PycQED_py3/blob/feature/DIOCal/pycqed/measurement/openql_experiments/openql_helpers.py#L52

whereas is wat set to '...output' in https://github.com/DiCarloLab-Delft/PycQED_py3/blob/feature/DIOCal/pycqed/measurement/openql_experiments/openql_helpers.py#L20

**Comment by jvanstraten** [comment]
OpenQL was resetting all options at the end of every call to compile() as a "fix" to test cases affecting each other. #380 modifies the behavior to something slightly more sane, although it doesn't fix the root cause (i.e. the context-sensitivity/global-state reliance of OpenQL's API).

**Comment by MiguelSMoreira** [comment]
The OpenQL Helpers have been modified to enforce that the 'output_dir' is set correctly across different experiments.
This has been successfully tested!
