### ISSUE TITLE
Housekeeping stuff/github stuff: develop, master, and main

### ISSUE THREAD

**Issue by DevelopDaily** [QE-Lab/OpenQL#385]
The peculiar setup of the branches of this project confuses me sometimes.

By convention, the "main" is the official branch, but the "main" is not used by this project.

The "master" is used by old projects as the official branch, but the "master" is stale in this project.

So, the "develop" is the official branch of this project, isn't it?

A little housekeeping could perhaps help newcomers.

**Comment by jvansomeren** [comment]
Yes, there is legacy here which could be confusing.
When we would want to update it, we should wait until GitHub facilitates migration (as they announce in
https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/); I'm relying on Jeroen here.
Next our customers and we will have to update our policies and implementations to comply.
I would like to see an estimate how much work that is; we would have to bring this to the table 
in the WP15 meetings with the LeoDiCarlo lab people.
And next, this work competes in resources with other work so a priority justification would be nice to have.

About the other legacy we have been working on to resolve the past year and still are working on
(documentation, seamless installation, continuous integration, modularizing the sources, expanding functionality to match targets and to match NISQ requirements) I'm happy to inform you in a top-down manner to give you insight in the dynamics around OpenQL development.

**Comment by jvansomeren** [comment]
Develop is the main branch that should always be consistent.
Real development is done in derived branches, one per issue/topic.
We are currently striving for a reduction of derived branches, kind of cleaning up the OpenQL repo.

**Comment by DevelopDaily** [comment]
Great. Thanks.
